# code used to build bookpedia entries from previous dbms

INSERT INTO ZLASTUSED (Z_ENT, Z_OPT, ZENTRY, Z2_ENTRY, ZDATE, ZNAME) 
	VALUES (5, 1, 31016, 3, -31588014848, 'Lesedatum unbekannt')


SELECT Z_ENT, Z_OPT, ZENTRY, Z2_ENTRY,  -31588014848 AS ZDATE, 'Lesedatum unbekannt' AS ZNAME
		FROM ZLASTUSED WHERE ZENTRY IN (
			SELECT Z_PK FROM ZENTRY WHERE ZPAGEMARK='A')


INSERT INTO ZLASTUSED (Z_ENT, Z_OPT, ZENTRY, Z2_ENTRY, ZDATE, ZNAME) 
			SELECT 5 AS Z_ENT, 1 AS Z_OPT, Z_PK AS ZENTRY, 3 AS Z2_ENTRY,  -31588014848 AS ZDATE, 'Lesedatum unbekannt' AS ZNAME
			FROM ZENTRY WHERE ZPAGEMARK='A'


INSERT INTO ZLASTUSED (Z_ENT, Z_OPT, ZENTRY, Z2_ENTRY, ZDATE, ZNAME) 
		SELECT DISTINCT Z_ENT, Z_OPT, ZENTRY, Z2_ENTRY,  -31588014848 AS ZDATE, 'Lesedatum unbekannt' AS ZNAME
		FROM ZLASTUSED WHERE ZENTRY IN (
			SELECT Z_PK FROM ZENTRY WHERE ZPAGEMARK='A')


SELECT *
FROM (SELECT A.Z_PK, A.ZCUSTOM2, COUNT(B.ZENTRY) AS CNT
FROM ZENTRY AS A
LEFT JOIN ZLASTUSED B
ON A.Z_PK = B.ZENTRY
GROUP BY B.ZENTRY)
WHERE ZCUSTOM2 != CNT
